name: Coding Agent - Create PR from issue
run-name: ${{ github.actor }} is creating a pull request from an issue description
on:
  workflow_dispatch:
    inputs:
      issue_number:
        description: 'Issue number to create a PR from'
        required: true
        type: number
jobs:
  create-pr:
    name: Generate pull request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Create branch
        run: git checkout -b issue-${{ inputs.issue_number }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload branch
        run: git push origin issue-${{ inputs.issue_number }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate code from issue description
        uses: widmoser/agent@c2245b7e57aabc3fc1ad8461522c2244fc5d94fd
        with:
          repository: ${{ github.repository }}
          branch: issue-${{ inputs.issue_number }}
          object_number: ${{ inputs.issue_number }}
          action: create
          model: openai/gpt-4o
          github_token: ${{ secrets.GITHUB_TOKEN }}
          openrouter_api_key: ${{ secrets.OPENROUTER_API_KEY }}
  