name: Coding Agent - Create PR from issue
run-name: ${{ github.actor }} is creating a pull request from an issue description
on:
  workflow_dispatch:
    inputs:
      issue_number:
        description: 'Issue number to create a PR from'
        required: true
        type: number
jobs:
  create-pr:
    name: Generate pull request
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create branch
        run: git checkout -b issue-${{ inputs.issue_number }}
      - name: Pull changes
        run: git pull origin issue-${{ inputs.issue_number }}
      - name: Upload branch
        run: git push --set-upstream origin issue-${{ inputs.issue_number }}
      - name: Create pull request
        run: gh pr create --title "Issue #${{ inputs.issue_number }}" --body "This PR is created from issue #${{ inputs.issue_number }} description." --base main --head issue-${{ inputs.issue_number }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - name: Generate code from issue description
      #   uses: widmoser/agent@main
      #   with:
      #     repository: ${{ github.repository }}
      #     branch: issue-${{ inputs.issue_number }}
      #     object_number: ${{ inputs.issue_number }}
      #     action: create
      #     model: openai/gpt-4o
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     openrouter_api_key: ${{ secrets.OPENROUTER_API_KEY }}
  