name: Coding Agent - Address PR review
run-name: ${{ github.actor }} is updating the pull request based on the review
on:
  pull_request_review:
    types: [submitted]
jobs:
  update-pr:
    name: Generate updated code
    if: contains(github.event.pull_request.labels.*.name, 'coding-agent')
    runs-on: ubuntu-latest

  